version: 2.1
jobs:
  run-test:
    docker:
      - image: circleci/node:14.18.1
    steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              name: Install npm dependencies
              command: npm install
          - run:
              name: Run API tests
              command: npm run test
workflows:
  run-test:
    jobs:
      - run-test
    
  
      
          
   